### GET Customers
GET http://localhost:4004/service/fromABAPtoCAPSvcs/Customers

### GET Customers
GET http://localhost:4004/service/fromABAPtoCAPSvcs/Customers
Authorization: Basic beth:password

### GET Northwind Customers
GET http://localhost:4004/service/fromABAPtoCAPSvcs/NorthwindCustomers


### GET S4 Sales Orders
GET http://localhost:4004/service/fromABAPtoCAPSvcs/S4SalesOrders
Authorization: Basic beth:password

### GET Customers
GET http://localhost:4004/service/fromABAPtoCAPSvcs/Customers('ALFKI')?$select=customerId,customerName,contactName,address,city,country,phone&$expand=orders
Authorization: Basic beth:password

### GET Customers
GET http://localhost:4004/service/fromABAPtoCAPSvcs/Customers('BONAP')/orders
Authorization: Basic beth:password