### GET metadata
GET http://localhost:4004/service/fromABAPtoCAPSvcs/$metadata


### GET Customers
GET http://localhost:4004/service/fromABAPtoCAPSvcs/Customers


### GET Northwind Customers
GET http://localhost:4004/service/fromABAPtoCAPSvcs/NorthwindCustomers


### GET S4 Sales Orders
GET http://localhost:4004/service/fromABAPtoCAPSvcs/S4SalesOrders


### GET Customers
GET http://localhost:4004/service/fromABAPtoCAPSvcs/Customers('ALFKI')?$select=customerId,customerName,contactName,address,city,country,phone&$expand=orders


### GET Customers
GET http://localhost:4004/service/fromABAPtoCAPSvcs/Customers('BONAP')/orders
